### ISSUE TITLE
App startup failed. Please check your data connection and try again.

### ISSUE THREAD

**Issue by juanpc2018** [paveloom-f/lbry-android#6]
> App startup failed. Please check your data connection and try again.
> If this problem persists, please email hello@lbry.com

since Android 11,
OS has a built-in censor and most Apps do Not work...

FireFox works, 
Opera VPN does Not, 
Opera Data saver works, 
Futo [GrayJay](https://grayjay.app/#download) does Not work, 
etc....

When AI wants to seriously [Ban](https://3.bp.blogspot.com/-TR--UEvsNxk/VZEXhLdfcKI/AAAAAAAABhk/M_ioXmzd_ok/s4096/cellphoneban.png) someone "Dangerous",
sends a "Limited Connection" 🚩 flag to the ONT modem,
and that is relayed to AndroidOS 11,
shutting down all communications, most apps.

some .apk work ok, because dont use Standard Android API or Libraries... "G... Play Services"
or use older, pre-censor.
or lazy software developers do Not follow the ISO9001 standard strictly.

LBRY app can be remote shut down by a Limited Connection 🚩Flag, like most other apks.
some Cellphone brands are Censorship resistant to a Limited Connection 🚩Flag Attack.

[This model](https://www.gsmarena.com/motorola_moto_g20-10828.php) is a NoGo

**Comment by paveloom** [comment]
This issue is out of scope of this repository.
