### ISSUE TITLE
request to update wallet server

### ISSUE THREAD

**Issue by ghost** [paveloom-f/lbry-android#7]
As you know LBRY, Inc. went defunct in 2023. Months later their wallet server was shut down making it impossible to load up LBRY wallets on LBRY Android using the private key file. Aside from that, the app still is functional.

Could you please update the wallet server on your fork of LBRY Android to the Odysee wallet server? 

a-hub1.odysee.com:50001

The reason why I bother to ask is that I still prefer LBRY Android to the Odysee app.

**Comment by paveloom** [comment]
Won't be looking into this at this time.
